#!/bin/bash

# In what directory is this script stored? (Expand to full pathname.)
hook_path="$(cd "$(dirname "$BASH_SOURCE")" ; pwd)"

if which cygpath >/dev/null
then # On Windows, with cygwin bash, convert to native Windows form
     hook_path="$(cygpath -m "$hook_path")"
fi

# If the user passed a repository pathname, go there.
[ -n "$1" ] && cd "$1"

# Whether or not the user passed a repository path, go to repo root.
cd "$(git rev-parse --show-toplevel)"
if [ ! -d .git/hooks ]; then
    echo "$1 not a valid repo" 1>&2
    exit 1
fi
#env
echo "installing hooks in repo $PWD"

cat > .git/hooks/pre-commit <<EOF
#!/bin/sh
exec "${hook_path}/coding_policy_git.py" --pre-commit
EOF

cat > .git/hooks/commit-msg <<EOF
#!/bin/sh
exec "${hook_path}/coding_policy_git.py" --commit-msg "\$1"
EOF

chmod +x .git/hooks/{pre-commit,commit-msg}
