#!/bin/sh

hook_path=${GIT_HOOK_REPO_PATH:-"../git-hooks"}
echo $hook_path

pushd $(git rev-parse --show-toplevel)
if [ ! -d .git/hooks ]; then
    echo "not a valid repo"
    exit 1
fi
#env
echo "installing hooks in current repo",$PWD
cp -v ${hook_path}/hooks/{pre-commit,commit-msg} .git/hooks
