#!/bin/sh

hook_path=${GIT_HOOK_REPO_PATH:-"../git-hooks"}
echo $hook_path

pushd $(git rev-parse --show-toplevel)
if [ ! -d .git/hooks ] || [ -e coding_policy_git.py ]; then
    echo "not a valid repo"
    exit 1
fi
#env
echo "installing hooks in current repo",$PWD
cp -v ${hook_path}/hooks/* .git/hooks
