name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - name: Install dependencies
      run: pip install tox
    - uses: pre-commit/action@v3.0.0
    - uses: codecov/codecov-action@v3